[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "~2.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.4.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/iconv.v1"
  version = "~1.1.1"

[[constraint]]
  name = "github.com/asaskevich/EventBus"
  revision = "68a521d7cbbb7a859c2608b06342f384b3bd5f5a"

# The following locks logrus to a particular version of x/sys
[[override]]
    name = "golang.org/x/sys"
    revision = "7dca6fe1f43775aa6d1334576870ff63f978f539"

[prune]
  go-tests = true
  unused-packages = true
