#!/bin/sh
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
./run.sh | telnet &
